### ISSUE TITLE
router failing to authenticate

### ISSUE THREAD

**Issue by zany130** [bypassrg/att#7]
I followed this guide to a T and used this python script https://github.com/iwleonards/extract-mfg
to get the certificates and then copy them to USB and then copy them into /jffs/EAP/
I then modified the conf to include the absolute path to each key and I got this 

/opt/usr/sbin/wpa_supplicant -dd -Dwired -ieth0 -c/jffs/EAP/wpa_supplicant.conf
Successfully initialized wpa_supplicant
eth0: Associated with 01:80:c2:00:00:03
WMM AC: Missing IEs
eth0: CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
eth0: CTRL-EVENT-EAP-STARTED EAP authentication started
eth0: CTRL-EVENT-EAP-FAILURE EAP authentication failed
eth0: CTRL-EVENT-EAP-STARTED EAP authentication started
eth0: CTRL-EVENT-EAP-STARTED EAP authentication started
eth0: CTRL-EVENT-EAP-STARTED EAP authentication started
eth0: CTRL-EVENT-EAP-FAILURE EAP authentication failed
eth0: CTRL-EVENT-EAP-STARTED EAP authentication started
eth0: CTRL-EVENT-EAP-STARTED EAP authentication started
eth0: CTRL-EVENT-EAP-STARTED EAP authentication started
eth0: CTRL-EVENT-EAP-FAILURE EAP authentication failed
eth0: CTRL-EVENT-EAP-STARTED EAP authentication started
eth0: CTRL-EVENT-EAP-STARTED EAP authentication started
eth0: CTRL-EVENT-EAP-STARTED EAP authentication started
eth0: CTRL-EVENT-EAP-FAILURE EAP authentication failed
eth0: CTRL-EVENT-EAP-STARTED EAP authentication started
eth0: CTRL-EVENT-EAP-STARTED EAP authentication started
eth0: CTRL-EVENT-EAP-STARTED EAP authentication started
eth0: CTRL-EVENT-EAP-FAILURE EAP authentication failed
eth0: CTRL-EVENT-EAP-STARTED EAP authentication started
eth0: CTRL-EVENT-EAP-STARTED EAP authentication started
eth0: CTRL-EVENT-EAP-STARTED EAP authentication started
eth0: CTRL-EVENT-EAP-FAILURE EAP authentication failed
eth0: CTRL-EVENT-EAP-STARTED EAP authentication started

**Comment by adamjungers** [comment]
Make sure your router is set to aggressive dhcp, and native ipv6. Make sure
you change the MAC address. What router are you using?

**Comment by zany130** [comment]
yeah I did all that well it was already set to agresive for me and I set ip6 to native I also enabled ai protection like the guide said to and sorry I should of specified which router I'm using this router 
https://www.asus.com/us/Networking/RT-AC3100/

**Comment by adamjungers** [comment]
Can you post a redacted copy of you .conf file?

**Comment by zany130** [comment]
this is how i have my conf 
```
# Generated by 802.1x Credential Extraction Tool
# Copyright (c) 2018-2019 devicelocksmith.com
# Version: 1.04 windows 386
# 
# Change file names to absolute paths
eapol_version=1
ap_scan=0
fast_reauth=1
network={
        ca_cert="/jffs/EAP/CA_001E46-R91VJ0#####.pem"
        client_cert="/jffs/EAP/Client_001E46-R91V######.pem"
        eap=TLS
        eapol_flags=0
        identity="20:F3:75:09:EF:A1" # Internet (ONT) interface MAC address must match this value
        key_mgmt=IEEE8021X
        phase1="allow_canned_success=1"
        private_key="/jffs/EAP/PrivateKey_PKCS1_001E46-R91VJ0#######.pem"
}
``` 
and then I have each key as a .pem in the same /jffs/EAP/ folder

**Comment by adamjungers** [comment]
Which architecture is that router? Run the command
uname -a

And post results, please.

**Comment by zany130** [comment]
i checked before and it was armv7 i think let me double check
EDIT:
admin@RT-AC3100-4A60:/tmp/home/root# uname -a
Linux RT-AC3100-4A60 2.6.36.4brcmarm #1 SMP PREEMPT Sat Apr 25 22:38:41 EDT 2020 armv7l ASUSWRT-Merlin

**Comment by adamjungers** [comment]
Use this as an example for your conf file, you will have to edit the direct
paths again on lines 7, I, 11, and 14.

After updating the conf file, run the following command

/opt/usr/sbin/wpa_supplicant -s -B -D wired -i eth0 -c
/jffs/EAP/wpa_supplicant.conf -P /var/run/wpa_supplicant.pid

**Comment by zany130** [comment]
same thing so I guess it just doesn't work on this model for some reason?

well i got a syntax error on the /jffs/EAP/wpa_supplicant.conf -P /var/run/wpa_supplicant.pid

/jffs/EAP/wpa_supplicant.conf: line 18: syntax error: unexpected "}"
but thats werid as i do have a matching { on line 9 

i tried rewriting the conf in visual studio code so that i can see better what im doing and it looks fine 

```
# Generated by 802.1x Credential Extraction Tool
# Copyright (c) 2018-2019 devicelocksmith.com
# Version: 1.04 windows 386
# 
# Change file names to absolute paths
eapol_version=1
ap_scan=0
fast_reauth=1
network={
        ca_cert="/jffs/EAP/CA_001E46-R91VJ0FE105151.pem"
        client_cert="/jffs/EAP/Client_001E46-R91VJ0FE105151.pem"
        eap=TLS
        eapol_flags=0
        identity="20:F3:75:09:EF:A1" # Internet (ONT) interface MAC address must match this value
        key_mgmt=IEEE8021X
        phase1="allow_canned_success=1"
        private_key="/jffs/EAP/PrivateKey_PKCS1_001E46-R91VJ0FE105151.pem"
}
```
i included the whole file name as I don't think that's really sensitive right ? its what's in the key files thats matters

**Comment by zany130** [comment]
i already put away my asus router so i couldn't get a pic directly form that but this is basicly how the file structure looks inside the EAP folder 
![Capture](https://user-images.githubusercontent.com/25832539/90947095-3d229c00-e401-11ea-8c8f-987652555de4.PNG)

**Comment by adamjungers** [comment]
It’s quite possible it won’t work on that router. Also very possible that
the packages need to be recompiled for that router. Also possible that you
need to do a completely fresh install. I don’t have time tomorrow but on
Sunday I can help you out on discord or zoom.

**Comment by zany130** [comment]
could be something else I have done on the router  I had already used entware and done some stuff doubt it but you never know. ill try doing it from scratch if not it's not too big of a deal since I already rooted the att modem I can just increase the nat table connection limit and do some other things (just have to figure out how to make it permanent or I can just re-run the commands every time I reboot the modem). now that I think about it I didn't even mention which modem I'm trying to bypass (shouldn't really matter though) its the BGW210. So I can just do those modifications and I actually bought a wifi 6 Asus router the ax86u I belive  and just connect that behind the modem

**Comment by adamjungers** [comment]
All of those are possibilities. I also used the bfw210. The certs don’t
really make a difference. Well let me know how that works out, if you need
some extra help let me know. I would much rather put that wifi 6 router
behind the ac3100.. honestly I think we just need to do a fresh install
with some modified commands.. it wants to work but I think we are missing a
few things.

Good luck

**Comment by mshuaic** [comment]
Please check the system date. `# date`
If the date is not the current date, you need to change it manually. 
- find the fake-hwclock.data (it may be in /jffs/opt/etc)
- edit it to the current date
- `# fake-hwclock load`

For some reason. it failed to automatically save the date in  **merlin build 384.18**. When I upgrade to  **384.19**, it fails to set the date to the current date and results in a failed authentication.

P.S. you can use -dd option to see more debug info for _wpa_supplicant_.
